name: Python-ImageProcessing_2022

channels:
    - conda-forge

dependencies:
    - python>=3.8
    - pip
    - numpy
    - scipy
    - scikit-image
    - opencv
    - matplotlib-base
    - joblib
    - napari[all]